// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwzzlyebdgbfstsaaohw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3enpseWViZGdiZnN0c2Fhb2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyMTIxMzgsImV4cCI6MjA3ODc4ODEzOH0.3AmkknaGImBxOk09fAmXvR6T_Q-t70ohTPhDUTnG4Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});